---
- name: Zabbix_Agent
  hosts: host
  become: true
  tasks:
    - name: Add Zabbix repository
      yum_repository:
        name: zabbix
        description: Zabbix Official Repository
        baseurl: https://repo.zabbix.com/zabbix/6.4/rhel/8/x86_64/
        gpgcheck: yes
        gpgkey: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX-A14FE591
        state: present

    - name: Check if Zabbix agent is installed
      stat:
        path: /etc/zabbix/zabbix_agentd.conf
      register: zabbix_agent_conf

    - name: Install Zabbix agent if not installed
      yum:
        name: zabbix-agent
        state: present
          #when: zabbix_agent_conf.stat.exists == False

    - name: Configure Zabbix agent
      replace:
        path: /etc/zabbix/zabbix_agentd.conf
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      loop:
        - { regexp: '^Server=127.0.0.1.*$', replace: 'Server=192.168.12.12' }
        - { regexp: '^ServerActive=127.0.0.1.*$', replace: 'ServerActive=192.168.12.12' }
      when: zabbix_agent_conf.stat.exists == True

